---
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:mysql://localhost:3306/synker
  properties:
    charSet: UTF-8
    ssl: false
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute